version: '3.8'
services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  nextjs:
    build:
      context: .
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      DATABASE_URL: "postgresql://postgres:mysecretpassword@postgres:5432/petadopt"
    ports:
      - "3003:3000"
      - '5555:5555'
volumes:
  postgres-data:
